name: debug_inspector
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  hive: ^2.0.5
  path_provider: ^2.0.9
  rxdart: ^0.27.3
#  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.debug_inspector.debug_inspector
        pluginClass: DebugInspectorPlugin
      ios:
        pluginClass: DebugInspectorPlugin
